### ISSUE TITLE
Vertical airspace limits

### ISSUE THREAD

**Issue by svoop** [svoop/aipp#13]
Vertical airspace limits (example shown here: LFAT) seem more correct in OpenFlightMaps than VAC after checking with France AIP.

**VAC**

<img width="635" alt="Screen Shot 2019-08-10 at 21 25 36" src="https://user-images.githubusercontent.com/7255/62826049-70f3a080-bbb5-11e9-9ef9-d3c48ebf60e8.png">

**AIP**

<img width="627" alt="Screen Shot 2019-08-10 at 21 25 39" src="https://user-images.githubusercontent.com/7255/62826058-7e108f80-bbb5-11e9-8e76-1b47c7eed33b.png">

https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_18_JUL_2019/FRANCE/AIRAC-2019-07-18/html/index-fr-FR.html

Reported by Stijn

**Comment by svoop** [comment]
I don't quite understand, both the VAC and the eAIP (and the data in OFMX) communicate the same vertical limits "FL 065 || 1500ft AMSL".

**Comment by Airbus320Driver** [comment]
What I found strange, is the overlap of CTR dimensions (SFC up to 2000') and TMA 12 (1500' up to FL 065) both on the chart and in eAIP. I can't remember if OFM showed 2000 ft or 1500 ft as upper limit for the CTR.  If OFM's CTR and TMA dimensions correctly reflect eAIP then you can disregard this comment.

**Comment by svoop** [comment]
It seems to be correct. Here's what the official map looks like:

<img width="699" alt="Screen Shot 2019-10-12 at 20 26 58" src="https://user-images.githubusercontent.com/7255/66706054-bb68d900-ed2e-11e9-8d7d-390772f83b70.png">

My interpretation: The CTR is only active 0700-1900, so at night, it's area is declassified from D to E between 2000 and 1500 as well as from D to G below 1500.

**Comment by svoop** [comment]
The vertical limits in the OFMX file match those in the eAIP.
