### ISSUE TITLE
LFQQ CTR vertical limits are different

### ISSUE THREAD

**Issue by svoop** [svoop/aipp#15]
<img width="604" alt="Screen Shot 2019-08-10 at 21 28 51" src="https://user-images.githubusercontent.com/7255/62826085-e495ad80-bbb5-11e9-88e0-ad6e1c299a68.png">

<img width="559" alt="Screen Shot 2019-08-10 at 21 28 57" src="https://user-images.githubusercontent.com/7255/62826087-e7909e00-bbb5-11e9-9145-4cec78c9075d.png">

Reported by Stijn

**Comment by svoop** [comment]
I don't see different vertical limits here, looks okay to me.

**Comment by Airbus320Driver** [comment]
The picture at the top depicts OFM, which shows TWO airspaces on top of each other (one in yellow, the other in red) for LFQQ.  It is unclear whether this is correct.

Based on the AIP (see table and visual approach chart), the CTR has rounded edges and extends from the surface to 2000 ft.

Therefore, it is not clear what the (almost) rectangular shape depicts.  Having said this, when you look at LFQQ on Skyvector.com, only the (almost) rectangular shape is shown.

**Comment by svoop** [comment]
I see. I'll have to take a look once the import with the OFM editor works (again). My guess: It's one of the more exotic temporary zones which are not printed on the official maps:

<img width="562" alt="Screen Shot 2019-10-12 at 20 47 28" src="https://user-images.githubusercontent.com/7255/66706345-89a54180-ed31-11e9-85d3-5d52f2d92bf9.png">

**Comment by svoop** [comment]
The duplicate (and wrong) Lille CTR is from an old import and does not exist in the current OFMX file.
