### ISSUE TITLE
Include obstacles announced via NOTAM

### ISSUE THREAD

**Issue by svoop** [svoop/aipp#26]
Some (temporary) obstacles are included as NOTAM navigational warnings (ID begins with the letter "W") such as the following:

```
W1674/22 NOTAMN
Q) LSAS/QXXXX/V/NBO/AW/000/076/4622N00700E001
A) LSEY B) 2210070700 C) 2211062359 EST
E) HIGHLINE OBST ERECTED 3.9 KM NNW HLP LEYSIN, BTN TOUR D AI AND TOUR DE MAYEN, RADIUS 0.5 KM (462225N0070017E RADIUS 0.3 NM).
MARKED WITH 6 WINDSOCKS.
MAX ALT UP TO 174 M AGL / 571 FT AGL, 2312 M AMSL / 7585 FT AMSL.
F) GND
G) 7600FT AMSL
```

(In this case, the "highline" seems to be a [slackline across a valley](https://sw-ke.facebook.com/leysintourisme/videos/1144441535649713/).)

**Comment by svoop** [comment]
Houston, we have a problem:

The Q item reads `QXXXX` which means first `XX` = "subject is other" and second `XX` = "condition is other". Such an unspecified NOTAM cannot be recognized as "obstacle" by AIPP or any other non-devine entity.

The NOTAM office has to use meaningful codes such as `QOBEC` which stands for `OB` = "obstacle" and `EC` = "erected".

Unless this policy change by the NOTAM office can be assured somehow, there's no way of including such obstacles.

**Comment by ovord** [comment]
bist sicher, dass das so veröffentlicht wurde? oder überschreibe sie das ggf in der cache version?

**Comment by svoop** [comment]
@ovord Dafür gibt es keinen Grund und keine Anzeichen. Schaue dir die anderen NOTAM vom 29. Oktober auf [notaminfo](https://notaminfo.com/oldnotams) an, alle anderen NOTAM haben aussagekräftige Codes, nur die Highline nicht.

**Comment by ovord** [comment]
@svoop wenns nur die highline ist, haben wir ja alleinstellungsmerkmal... ;)

**Comment by ovord** [comment]
@svoop muss ich nochmal mit skyguide typ reden oder :(

**Comment by svoop** [comment]
> muss ich nochmal mit skyguide typ reden oder :(

Yep, oder du schliesst ihn mit mir kurz, damit ich ihn selber fragen kann.

**Comment by svoop** [comment]
@philhug Ich versuche gerade, das NOTAM W1674/22 über das `internal-api` zu finden (mit dem Playground). Über die Timestamps kommt es aber nicht raus, auch nicht, wenn ich von 0 bis heute suche. Daher ein paar Fragen:

* Wäre es möglich, noch einen filter nach "name" oder "rawNotam" einzubauen? Also z.B. um mit `"name": "B1192/22-%"` nach dem NOTAM `"name": "B1192/22-LSAS"` zu finden. (Aufwendige Wildcards machen bestimmt keinen Sinn, aber vielleicht solche, die dahinter von der Db ohnehin erkannt werden, z.B. das `%` von SQL `ilike`?
* Git das API alle Treffer aus oder gibt's eine maximal Trefferzahl, bei der Schluss ist?
* Wie lange werden die NOTAM in der Db behalten? Oder anders: Mit welchen Kriterien werden die alten NOTAM aufgeräumt?

**Comment by svoop** [comment]
Der Vollständigkeit halber hier noch die Antworten von Skyguide zu W1674/22:

> Auf der DABS werden grundsätzlich Warnings QW… Informationen publiziert. Somit widersprechen Hindernisse dem Sinn des DABS. Auch werden Hindernisse nicht in der Serie W publiziert, was eine Voraussetzung ist, um auf das DABS zu kommen.
>
> Dennoch wurde vom LIFS/BAZL aus bestimmten Grund entschieden, dieses spezielle Hindernis auf DABS zu publizieren. Da es keinen entsprechenden QW… Code für Highlines gibt, und es ein Serie W NOTAM sein muss, wurde der QXXXX Code genommen. Dieses Procedure ist so in unseren Arbeitsunterlagen festgehalten.

**Comment by svoop** [comment]
@ovord Ich habe gerad W1674/22 durch den Parser gelassen und das hier fällt hinten raus:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/7255/202864385-d8479035-5b05-4d2f-b4dc-56bbb0b8581e.png">

Sieht soweit okay aus, oder?

Ist allerdings nicht als Obstacle codiert, sondern als Luftraum RAS (regulated airspace). Das liegt daran, dass ich aktuell kein NOTAM als Obstacle codiere. (Und DABS sollte eigentlich ja auch gar keine Obstacles enthaten.)

Eigentlich hätte diese RAS im Oktober also angezeigt werden sollen – und vielleicht war es auch so. Was meinst du: So lassen oder als Obstacle codieren?

**Comment by svoop** [comment]
@ovord FYI

Die relevanten NOTAM filtere ich derzeit wie folgt, es muss eins der beiden Kriterien erfüllt sein:

* Scope ist `W` (warning) oder `AW` (aerodrome and warning)
* Subject ist `AT` (terminal control area), also der Code beginnend mit`QATxx`

Diese Filter musste ich auf der Basis einiger DABS raten, denn offengelegt wird das nirgendwo.Die Aussage von Skyguide deutet nun darauf hin, dass sie eigentlich nur nach dem Subject auswählen:

> Auf der DABS werden grundsätzlich Warnings QW… Informationen publiziert.

Das wären also alle NOTAM mit dem Code beginnend mit `QWxxx`.

Ich beobachte das die nächste Woche etwas genauer und passe ggf. meinen Filter entsprechend an. In dem Fall würde dann die Highline mit `QXXXX` durchfallen, ausser, wir gehen davon aus, dass das dann immer Obstacles sind.

**Comment by svoop** [comment]
Hab grad noch ein paar Filterdetails von Skyguide erhalten:

>Sie haben recht. Unter NAV Warnings fallen auch noch weitere NOTAM Publikationen mit entsprechenden Q Codes (z.B. QRR QRD QRT QAT..etc). Zusammengefasst sind das folgende Aktivitäten für DABS:
>
>* Activation of PRD areas and TEMPO TMA
>* TEMPO TMA/CTR activations
>* Military firing above 250m/AGL
>
>(Siehe AIP GEN 3.1 – 5 Daily Airspace Bulletin Switzerland (DABS))

**Comment by svoop** [comment]
Implementierung derzeit nicht vorgesehen.
