### ISSUE TITLE
ATIS missing

### ISSUE THREAD

**Issue by svoop** [svoop/aipp#8]
e.g. LFMN

<img width="184" alt="Screen Shot 2019-08-10 at 20 58 57" src="https://user-images.githubusercontent.com/7255/62825804-b7df9700-bbb1-11e9-9fbd-3d2f769b83ac.png">

<img width="418" alt="Screen Shot 2019-08-10 at 20 59 05" src="https://user-images.githubusercontent.com/7255/62825807-ba41f100-bbb1-11e9-91ae-d0798d9675cc.png">

Reported by Stijn

**Comment by svoop** [comment]
Both are present in the OFMX export:

<img width="439" alt="Screen Shot 2019-10-11 at 21 44 15" src="https://user-images.githubusercontent.com/7255/66680238-56e74480-ec70-11e9-958b-19db061e2e36.png">

**Comment by svoop** [comment]
@ovord Kannst du kontrollieren, ob die ATIS übernommen werden? Im Export sind sie eigentlich drin.

**Comment by svoop** [comment]
@ovord Kann ich dieses Issue schliessen?

**Comment by ovord** [comment]
yes please, why github? @svoop

**Comment by svoop** [comment]
Altes Issue, auf GitHub sollen eigentlich nur noch grundsätzliche Probleme mit AIPP, nicht mit den einzelnen Adaptern wie LF oder LS.
